export const COUNTRIES = [
  {
    label: "Afghanistan",
    value: "afghanistan",
    flag: "https://flagcdn.com/w80/af.png",
  },
  {
    label: "Albania",
    value: "albania",
    flag: "https://flagcdn.com/w80/al.png",
  },
  {
    label: "Algeria",
    value: "algeria",
    flag: "https://flagcdn.com/w80/dz.png",
  },
  {
    label: "Andorra",
    value: "andorra",
    flag: "https://flagcdn.com/w80/ad.png",
  },
  { label: "Angola", value: "angola", flag: "https://flagcdn.com/w80/ao.png" },
  {
    label: "Antigua and Barbuda",
    value: "antigua_and_barbuda",
    flag: "https://flagcdn.com/w80/ag.png",
  },
  {
    label: "Argentina",
    value: "argentina",
    flag: "https://flagcdn.com/w80/ar.png",
  },
  {
    label: "Armenia",
    value: "armenia",
    flag: "https://flagcdn.com/w80/am.png",
  },
  {
    label: "Australia",
    value: "australia",
    flag: "https://flagcdn.com/w80/au.png",
  },
  {
    label: "Austria",
    value: "austria",
    flag: "https://flagcdn.com/w80/at.png",
  },
  {
    label: "Azerbaijan",
    value: "azerbaijan",
    flag: "https://flagcdn.com/w80/az.png",
  },
  {
    label: "Bahamas",
    value: "bahamas",
    flag: "https://flagcdn.com/w80/bs.png",
  },
  {
    label: "Bahrain",
    value: "bahrain",
    flag: "https://flagcdn.com/w80/bh.png",
  },
  {
    label: "Bangladesh",
    value: "bangladesh",
    flag: "https://flagcdn.com/w80/bd.png",
  },
  {
    label: "Barbados",
    value: "barbados",
    flag: "https://flagcdn.com/w80/bb.png",
  },
  {
    label: "Belarus",
    value: "belarus",
    flag: "https://flagcdn.com/w80/by.png",
  },
  {
    label: "Belgium",
    value: "belgium",
    flag: "https://flagcdn.com/w80/be.png",
  },
  { label: "Belize", value: "belize", flag: "https://flagcdn.com/w80/bz.png" },
  { label: "Benin", value: "benin", flag: "https://flagcdn.com/w80/bj.png" },
  { label: "Bhutan", value: "bhutan", flag: "https://flagcdn.com/w80/bt.png" },
  {
    label: "Bolivia",
    value: "bolivia",
    flag: "https://flagcdn.com/w80/bo.png",
  },
  {
    label: "Bosnia and Herzegovina",
    value: "bosnia_and_herzegovina",
    flag: "https://flagcdn.com/w80/ba.png",
  },
  {
    label: "Botswana",
    value: "botswana",
    flag: "https://flagcdn.com/w80/bw.png",
  },
  { label: "Brazil", value: "brazil", flag: "https://flagcdn.com/w80/br.png" },
  { label: "Brunei", value: "brunei", flag: "https://flagcdn.com/w80/bn.png" },
  {
    label: "Bulgaria",
    value: "bulgaria",
    flag: "https://flagcdn.com/w80/bg.png",
  },
  {
    label: "Burkina Faso",
    value: "burkina_faso",
    flag: "https://flagcdn.com/w80/bf.png",
  },
  {
    label: "Burundi",
    value: "burundi",
    flag: "https://flagcdn.com/w80/bi.png",
  },
  {
    label: "Cambodia",
    value: "cambodia",
    flag: "https://flagcdn.com/w80/kh.png",
  },
  {
    label: "Cameroon",
    value: "cameroon",
    flag: "https://flagcdn.com/w80/cm.png",
  },
  { label: "Canada", value: "canada", flag: "https://flagcdn.com/w80/ca.png" },
  {
    label: "Cape Verde",
    value: "cape_verde",
    flag: "https://flagcdn.com/w80/cv.png",
  },
  {
    label: "Central African Republic",
    value: "central_african_republic",
    flag: "https://flagcdn.com/w80/cf.png",
  },
  { label: "Chad", value: "chad", flag: "https://flagcdn.com/w80/td.png" },
  { label: "Chile", value: "chile", flag: "https://flagcdn.com/w80/cl.png" },
  { label: "China", value: "china", flag: "https://flagcdn.com/w80/cn.png" },
  {
    label: "Colombia",
    value: "colombia",
    flag: "https://flagcdn.com/w80/co.png",
  },
  {
    label: "Comoros",
    value: "comoros",
    flag: "https://flagcdn.com/w80/km.png",
  },
  { label: "Congo", value: "congo", flag: "https://flagcdn.com/w80/cg.png" },
  {
    label: "Costa Rica",
    value: "costa_rica",
    flag: "https://flagcdn.com/w80/cr.png",
  },
  {
    label: "Croatia",
    value: "croatia",
    flag: "https://flagcdn.com/w80/hr.png",
  },
  { label: "Cuba", value: "cuba", flag: "https://flagcdn.com/w80/cu.png" },
  { label: "Cyprus", value: "cyprus", flag: "https://flagcdn.com/w80/cy.png" },
  {
    label: "Czech Republic",
    value: "czech_republic",
    flag: "https://flagcdn.com/w80/cz.png",
  },
  {
    label: "Denmark",
    value: "denmark",
    flag: "https://flagcdn.com/w80/dk.png",
  },
  {
    label: "Djibouti",
    value: "djibouti",
    flag: "https://flagcdn.com/w80/dj.png",
  },
  {
    label: "Dominica",
    value: "dominica",
    flag: "https://flagcdn.com/w80/dm.png",
  },
  {
    label: "Dominican Republic",
    value: "dominican_republic",
    flag: "https://flagcdn.com/w80/do.png",
  },
  {
    label: "East Timor",
    value: "east_timor",
    flag: "https://flagcdn.com/w80/tl.png",
  },
  {
    label: "Ecuador",
    value: "ecuador",
    flag: "https://flagcdn.com/w80/ec.png",
  },
  { label: "Egypt", value: "egypt", flag: "https://flagcdn.com/w80/eg.png" },
  {
    label: "El Salvador",
    value: "el_salvador",
    flag: "https://flagcdn.com/w80/sv.png",
  },
  {
    label: "Equatorial Guinea",
    value: "equatorial_guinea",
    flag: "https://flagcdn.com/w80/gq.png",
  },
  {
    label: "Eritrea",
    value: "eritrea",
    flag: "https://flagcdn.com/w80/er.png",
  },
  {
    label: "Estonia",
    value: "estonia",
    flag: "https://flagcdn.com/w80/ee.png",
  },
  {
    label: "Ethiopia",
    value: "ethiopia",
    flag: "https://flagcdn.com/w80/et.png",
  },
  { label: "Fiji", value: "fiji", flag: "https://flagcdn.com/w80/fj.png" },
  {
    label: "Finland",
    value: "finland",
    flag: "https://flagcdn.com/w80/fi.png",
  },
  { label: "France", value: "france", flag: "https://flagcdn.com/w80/fr.png" },
  { label: "Gabon", value: "gabon", flag: "https://flagcdn.com/w80/ga.png" },
  { label: "Gambia", value: "gambia", flag: "https://flagcdn.com/w80/gm.png" },
  {
    label: "Georgia",
    value: "georgia",
    flag: "https://flagcdn.com/w80/ge.png",
  },
  {
    label: "Germany",
    value: "germany",
    flag: "https://flagcdn.com/w80/de.png",
  },
  { label: "Ghana", value: "ghana", flag: "https://flagcdn.com/w80/gh.png" },
  { label: "Greece", value: "greece", flag: "https://flagcdn.com/w80/gr.png" },
  {
    label: "Grenada",
    value: "grenada",
    flag: "https://flagcdn.com/w80/gd.png",
  },
  {
    label: "Guatemala",
    value: "guatemala",
    flag: "https://flagcdn.com/w80/gt.png",
  },
  { label: "Guinea", value: "guinea", flag: "https://flagcdn.com/w80/gn.png" },
  {
    label: "Guinea-Bissau",
    value: "guinea_bissau",
    flag: "https://flagcdn.com/w80/gw.png",
  },
  { label: "Guyana", value: "guyana", flag: "https://flagcdn.com/w80/gy.png" },
  { label: "Haiti", value: "haiti", flag: "https://flagcdn.com/w80/ht.png" },
  {
    label: "Honduras",
    value: "honduras",
    flag: "https://flagcdn.com/w80/hn.png",
  },
  {
    label: "Hungary",
    value: "hungary",
    flag: "https://flagcdn.com/w80/hu.png",
  },
  {
    label: "Iceland",
    value: "iceland",
    flag: "https://flagcdn.com/w80/is.png",
  },
  { label: "India", value: "india", flag: "https://flagcdn.com/w80/in.png" },
  {
    label: "Indonesia",
    value: "indonesia",
    flag: "https://flagcdn.com/w80/id.png",
  },
  { label: "Iran", value: "iran", flag: "https://flagcdn.com/w80/ir.png" },
  { label: "Iraq", value: "iraq", flag: "https://flagcdn.com/w80/iq.png" },
  {
    label: "Ireland",
    value: "ireland",
    flag: "https://flagcdn.com/w80/ie.png",
  },
  { label: "Israel", value: "israel", flag: "https://flagcdn.com/w80/il.png" },
  { label: "Italy", value: "italy", flag: "https://flagcdn.com/w80/it.png" },
  {
    label: "Ivory Coast",
    value: "ivory_coast",
    flag: "https://flagcdn.com/w80/ci.png",
  },
  {
    label: "Jamaica",
    value: "jamaica",
    flag: "https://flagcdn.com/w80/jm.png",
  },
  { label: "Japan", value: "japan", flag: "https://flagcdn.com/w80/jp.png" },
  { label: "Jordan", value: "jordan", flag: "https://flagcdn.com/w80/jo.png" },
  {
    label: "Kazakhstan",
    value: "kazakhstan",
    flag: "https://flagcdn.com/w80/kz.png",
  },
  { label: "Kenya", value: "kenya", flag: "https://flagcdn.com/w80/ke.png" },
  {
    label: "Kiribati",
    value: "kiribati",
    flag: "https://flagcdn.com/w80/ki.png",
  },
  {
    label: "North Korea",
    value: "north_korea",
    flag: "https://flagcdn.com/w80/kp.png",
  },
  {
    label: "South Korea",
    value: "south_korea",
    flag: "https://flagcdn.com/w80/kr.png",
  },
  { label: "Kuwait", value: "kuwait", flag: "https://flagcdn.com/w80/kw.png" },
  {
    label: "Kyrgyzstan",
    value: "kyrgyzstan",
    flag: "https://flagcdn.com/w80/kg.png",
  },
  { label: "Laos", value: "laos", flag: "https://flagcdn.com/w80/la.png" },
  { label: "Latvia", value: "latvia", flag: "https://flagcdn.com/w80/lv.png" },
  {
    label: "Lebanon",
    value: "lebanon",
    flag: "https://flagcdn.com/w80/lb.png",
  },
  {
    label: "Lesotho",
    value: "lesotho",
    flag: "https://flagcdn.com/w80/ls.png",
  },
  {
    label: "Liberia",
    value: "liberia",
    flag: "https://flagcdn.com/w80/lr.png",
  },
  { label: "Libya", value: "libya", flag: "https://flagcdn.com/w80/ly.png" },
  {
    label: "Liechtenstein",
    value: "liechtenstein",
    flag: "https://flagcdn.com/w80/li.png",
  },
  {
    label: "Lithuania",
    value: "lithuania",
    flag: "https://flagcdn.com/w80/lt.png",
  },
  {
    label: "Luxembourg",
    value: "luxembourg",
    flag: "https://flagcdn.com/w80/lu.png",
  },
  {
    label: "Macedonia",
    value: "macedonia",
    flag: "https://flagcdn.com/w80/mk.png",
  },
  {
    label: "Madagascar",
    value: "madagascar",
    flag: "https://flagcdn.com/w80/mg.png",
  },
  { label: "Malawi", value: "malawi", flag: "https://flagcdn.com/w80/mw.png" },
  {
    label: "Malaysia",
    value: "malaysia",
    flag: "https://flagcdn.com/w80/my.png",
  },
  {
    label: "Maldives",
    value: "maldives",
    flag: "https://flagcdn.com/w80/mv.png",
  },
  { label: "Mali", value: "mali", flag: "https://flagcdn.com/w80/ml.png" },
  { label: "Malta", value: "malta", flag: "https://flagcdn.com/w80/mt.png" },
  {
    label: "Marshall Islands",
    value: "marshall_islands",
    flag: "https://flagcdn.com/w80/mh.png",
  },
  {
    label: "Mauritania",
    value: "mauritania",
    flag: "https://flagcdn.com/w80/mr.png",
  },
  {
    label: "Mauritius",
    value: "mauritius",
    flag: "https://flagcdn.com/w80/mu.png",
  },
  { label: "Mexico", value: "mexico", flag: "https://flagcdn.com/w80/mx.png" },
  {
    label: "Micronesia",
    value: "micronesia",
    flag: "https://flagcdn.com/w80/fm.png",
  },
  {
    label: "Moldova",
    value: "moldova",
    flag: "https://flagcdn.com/w80/md.png",
  },
  { label: "Monaco", value: "monaco", flag: "https://flagcdn.com/w80/mc.png" },
  {
    label: "Mongolia",
    value: "mongolia",
    flag: "https://flagcdn.com/w80/mn.png",
  },
  {
    label: "Montenegro",
    value: "montenegro",
    flag: "https://flagcdn.com/w80/me.png",
  },
  {
    label: "Morocco",
    value: "morocco",
    flag: "https://flagcdn.com/w80/ma.png",
  },
  {
    label: "Mozambique",
    value: "mozambique",
    flag: "https://flagcdn.com/w80/mz.png",
  },
  {
    label: "Myanmar",
    value: "myanmar",
    flag: "https://flagcdn.com/w80/mm.png",
  },
  {
    label: "Namibia",
    value: "namibia",
    flag: "https://flagcdn.com/w80/na.png",
  },
  { label: "Nauru", value: "nauru", flag: "https://flagcdn.com/w80/nr.png" },
  { label: "Nepal", value: "nepal", flag: "https://flagcdn.com/w80/np.png" },
  {
    label: "Netherlands",
    value: "netherlands",
    flag: "https://flagcdn.com/w80/nl.png",
  },
  {
    label: "New Zealand",
    value: "new_zealand",
    flag: "https://flagcdn.com/w80/nz.png",
  },
  {
    label: "Nicaragua",
    value: "nicaragua",
    flag: "https://flagcdn.com/w80/ni.png",
  },
  { label: "Niger", value: "niger", flag: "https://flagcdn.com/w80/ne.png" },
  {
    label: "Nigeria",
    value: "nigeria",
    flag: "https://flagcdn.com/w80/ng.png",
  },
  { label: "Norway", value: "norway", flag: "https://flagcdn.com/w80/no.png" },
  { label: "Oman", value: "oman", flag: "https://flagcdn.com/w80/om.png" },
  {
    label: "Pakistan",
    value: "pakistan",
    flag: "https://flagcdn.com/w80/pk.png",
  },
  { label: "Palau", value: "palau", flag: "https://flagcdn.com/w80/pw.png" },
  { label: "Panama", value: "panama", flag: "https://flagcdn.com/w80/pa.png" },
  {
    label: "Papua New Guinea",
    value: "papua_new_guinea",
    flag: "https://flagcdn.com/w80/pg.png",
  },
  {
    label: "Paraguay",
    value: "paraguay",
    flag: "https://flagcdn.com/w80/py.png",
  },
  { label: "Peru", value: "peru", flag: "https://flagcdn.com/w80/pe.png" },
  {
    label: "Philippines",
    value: "philippines",
    flag: "https://flagcdn.com/w80/ph.png",
  },
  { label: "Poland", value: "poland", flag: "https://flagcdn.com/w80/pl.png" },
  {
    label: "Portugal",
    value: "portugal",
    flag: "https://flagcdn.com/w80/pt.png",
  },
  { label: "Qatar", value: "qatar", flag: "https://flagcdn.com/w80/qa.png" },
  {
    label: "Romania",
    value: "romania",
    flag: "https://flagcdn.com/w80/ro.png",
  },
  { label: "Russia", value: "russia", flag: "https://flagcdn.com/w80/ru.png" },
  { label: "Rwanda", value: "rwanda", flag: "https://flagcdn.com/w80/rw.png" },
  {
    label: "Saint Kitts and Nevis",
    value: "saint_kitts_and_nevis",
    flag: "https://flagcdn.com/w80/kn.png",
  },
  {
    label: "Saint Lucia",
    value: "saint_lucia",
    flag: "https://flagcdn.com/w80/lc.png",
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint_vincent_and_the_grenadines",
    flag: "https://flagcdn.com/w80/vc.png",
  },
  { label: "Samoa", value: "samoa", flag: "https://flagcdn.com/w80/ws.png" },
  {
    label: "San Marino",
    value: "san_marino",
    flag: "https://flagcdn.com/w80/sm.png",
  },
  {
    label: "Sao Tome and Principe",
    value: "sao_tome_and_principe",
    flag: "https://flagcdn.com/w80/st.png",
  },
  {
    label: "Saudi Arabia",
    value: "saudi_arabia",
    flag: "https://flagcdn.com/w80/sa.png",
  },
  {
    label: "Senegal",
    value: "senegal",
    flag: "https://flagcdn.com/w80/sn.png",
  },
  { label: "Serbia", value: "serbia", flag: "https://flagcdn.com/w80/rs.png" },
  {
    label: "Seychelles",
    value: "seychelles",
    flag: "https://flagcdn.com/w80/sc.png",
  },
  {
    label: "Sierra Leone",
    value: "sierra_leone",
    flag: "https://flagcdn.com/w80/sl.png",
  },
  {
    label: "Singapore",
    value: "singapore",
    flag: "https://flagcdn.com/w80/sg.png",
  },
  {
    label: "Slovakia",
    value: "slovakia",
    flag: "https://flagcdn.com/w80/sk.png",
  },
  {
    label: "Slovenia",
    value: "slovenia",
    flag: "https://flagcdn.com/w80/si.png",
  },
  {
    label: "Solomon Islands",
    value: "solomon_islands",
    flag: "https://flagcdn.com/w80/sb.png",
  },
  {
    label: "Somalia",
    value: "somalia",
    flag: "https://flagcdn.com/w80/so.png",
  },
  {
    label: "South Africa",
    value: "south_africa",
    flag: "https://flagcdn.com/w80/za.png",
  },
  {
    label: "South Sudan",
    value: "south_sudan",
    flag: "https://flagcdn.com/w80/ss.png",
  },
  { label: "Spain", value: "spain", flag: "https://flagcdn.com/w80/es.png" },
  {
    label: "Sri Lanka",
    value: "sri_lanka",
    flag: "https://flagcdn.com/w80/lk.png",
  },
  { label: "Sudan", value: "sudan", flag: "https://flagcdn.com/w80/sd.png" },
  {
    label: "Suriname",
    value: "suriname",
    flag: "https://flagcdn.com/w80/sr.png",
  },
  {
    label: "Swaziland",
    value: "swaziland",
    flag: "https://flagcdn.com/w80/sz.png",
  },
  { label: "Sweden", value: "sweden", flag: "https://flagcdn.com/w80/se.png" },
  {
    label: "Switzerland",
    value: "switzerland",
    flag: "https://flagcdn.com/w80/ch.png",
  },
  { label: "Syria", value: "syria", flag: "https://flagcdn.com/w80/sy.png" },
  { label: "Taiwan", value: "taiwan", flag: "https://flagcdn.com/w80/tw.png" },
  {
    label: "Tajikistan",
    value: "tajikistan",
    flag: "https://flagcdn.com/w80/tj.png",
  },
  {
    label: "Tanzania",
    value: "tanzania",
    flag: "https://flagcdn.com/w80/tz.png",
  },
  {
    label: "Thailand",
    value: "thailand",
    flag: "https://flagcdn.com/w80/th.png",
  },
  { label: "Togo", value: "togo", flag: "https://flagcdn.com/w80/tg.png" },
  { label: "Tonga", value: "tonga", flag: "https://flagcdn.com/w80/to.png" },
  {
    label: "Trinidad and Tobago",
    value: "trinidad_and_tobago",
    flag: "https://flagcdn.com/w80/tt.png",
  },
  {
    label: "Tunisia",
    value: "tunisia",
    flag: "https://flagcdn.com/w80/tn.png",
  },
  { label: "Turkey", value: "turkey", flag: "https://flagcdn.com/w80/tr.png" },
  {
    label: "Turkmenistan",
    value: "turkmenistan",
    flag: "https://flagcdn.com/w80/tm.png",
  },
  { label: "Tuvalu", value: "tuvalu", flag: "https://flagcdn.com/w80/tv.png" },
  { label: "Uganda", value: "uganda", flag: "https://flagcdn.com/w80/ug.png" },
  {
    label: "Ukraine",
    value: "ukraine",
    flag: "https://flagcdn.com/w80/ua.png",
  },
  {
    label: "United Arab Emirates",
    value: "united_arab_emirates",
    flag: "https://flagcdn.com/w80/ae.png",
  },
  {
    label: "United Kingdom",
    value: "united_kingdom",
    flag: "https://flagcdn.com/w80/gb.png",
  },
  {
    label: "United States",
    value: "united_states",
    flag: "https://flagcdn.com/w80/us.png",
  },
  {
    label: "Uruguay",
    value: "uruguay",
    flag: "https://flagcdn.com/w80/uy.png",
  },
  {
    label: "Uzbekistan",
    value: "uzbekistan",
    flag: "https://flagcdn.com/w80/uz.png",
  },
  {
    label: "Vanuatu",
    value: "vanuatu",
    flag: "https://flagcdn.com/w80/vu.png",
  },
  {
    label: "Vatican City",
    value: "vatican_city",
    flag: "https://flagcdn.com/w80/va.png",
  },
  {
    label: "Venezuela",
    value: "venezuela",
    flag: "https://flagcdn.com/w80/ve.png",
  },
  {
    label: "Vietnam",
    value: "vietnam",
    flag: "https://flagcdn.com/w80/vn.png",
  },
  { label: "Yemen", value: "yemen", flag: "https://flagcdn.com/w80/ye.png" },
  { label: "Zambia", value: "zambia", flag: "https://flagcdn.com/w80/zm.png" },
  {
    label: "Zimbabwe",
    value: "zimbabwe",
    flag: "https://flagcdn.com/w80/zw.png",
  },
];
