export const INDIA_STATES = [
    { label: 'Andhra Pradesh', value: 'ANDHRA_PRADESH' },
    { label: 'Arunachal Pradesh', value: 'ARUNACHAL_PRADESH' },
    { label: 'Assam', value: 'ASSAM' },
    { label: 'Bihar', value: 'BIHAR' },
    { label: 'Chhattisgarh', value: 'CHHATTISGARH' },
    { label: 'Goa', value: 'GOA' },
    { label: 'Gujarat', value: 'GUJARAT' },
    { label: 'Haryana', value: 'HARYANA' },
    { label: 'Himachal Pradesh', value: 'HIMACHAL_PRADESH' },
    { label: 'Jharkhand', value: 'JHARKHAND' },
    { label: 'Karnataka', value: 'KARNATAKA' },
    { label: 'Kerala', value: 'KERALA' },
    { label: 'Madhya Pradesh ', value: 'MADHYA_PRADESH' },
    { label: 'Maharashtra ', value: 'MAHARASHTRA' },
    { label: 'Manipur ', value: 'MANIPUR' },
    { label: 'Meghalaya ', value: 'MEGHALAYA' },
    { label: 'Mizoram ', value: 'MIZORAM' },
    { label: 'Nagaland ', value: 'NAGALAND' },
    { label: 'Odisha ', value: 'ODISHA' },
    { label: 'Punjab ', value: 'PUNJAB' },
    { label: 'Rajasthan ', value: 'RAJASTHAN' },
    { label: 'Sikkim ', value: 'SIKKIM' },
    { label: 'Tamil Nadu ', value: 'TAMIL_NADU' },
    { label: 'Telangana ', value: 'TELANGANA' },
    { label: 'Tripura ', value: 'TRIPURA' },
    { label: 'Uttarakhand ', value: 'UTTARAKHAND' },
    { label: 'Uttar Pradesh ', value: 'UTTAR_PRADESH' },
    { label: 'West Bengal ', value: 'WEST_BENGAL' },
    { label: 'Andaman and Nicobar Islands ', value: 'ANDAMAN_AND_NICOBAR_ISLANDS' },
    { label: 'Chandigarh ', value: 'CHANDIGARH' },
    { label: 'Dadra and Nagar Haveli and Daman & Diu', value: 'DADRA_AND_NAGAR_HAVELI_AND_DAMAN_DIU' },
    { label: 'Delhi NCR ', value: 'DELHI' },
    { label: 'Jammu & Kashmir ', value: 'JAMMU_AND_KASHMIR' },
    { label: 'Ladakh ', value: 'LADAKH' },
    { label: 'Lakshadweep ', value: 'LAKSHADWEEP' },
    { label: 'Puducherry ', value: 'PUDUCHERRY' }
  ];