import { VisaForm } from '../../types/form';

export const australiaVisaForm: VisaForm = {
  id: 'australia-visitor-visa',
  countryCode: 'AU',
  name: 'Australia Visitor Visa',
  description: 'Application for an Australia Visitor Visa',
  steps: [
    {
      title: 'Application Context',
      group: 'eligibility',
      showDocuments: false
    },
    {
      title: 'Personal Information',
      group: 'personal',
      showDocuments: false
    },
    {
      title: 'Travel Information',
      group: 'travel',
      showDocuments: false
    },
    {
      title: 'Purpose of Stay',
      group: 'travel',
      showDocuments: false
    }
  ],
  fields: [
    // Application Context Section
    {
      id: 'applicationContextHeader',
      group: 'eligibility',
      type: 'header',
      label: 'Application context'
    },
    {
      id: 'currentLocationHeader',
      group: 'eligibility',
      type: 'header',
      label: 'Current location'
    },
    {
      id: 'outsideAustralia',
      group: 'eligibility',
      type: 'select',
      label: 'Is the applicant currently outside Australia?',
      required: true,
      options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' }
      ]
    },
    {
      id: 'currentLocationInfo',
      group: 'eligibility',
      type: 'info',
      label: '',
      content: ['Give the current location of the applicant and their legal status at this location.']
    },
    {
      id: 'currentLocation',
      group: 'eligibility',
      type: 'select',
      label: 'Current location',
      required: true,
      options: [
        { label: 'Afghanistan', value: 'afghanistan' },
        { label: 'Albania', value: 'albania' },
        { label: 'Algeria', value: 'algeria' },
        { label: 'Andorra', value: 'andorra' },
        { label: 'Angola', value: 'angola' },
        { label: 'Antigua and Barbuda', value: 'antigua_and_barbuda' },
        { label: 'Argentina', value: 'argentina' },
        { label: 'Armenia', value: 'armenia' },
        { label: 'Australia', value: 'australia' },
        { label: 'Austria', value: 'austria' },
        { label: 'Azerbaijan', value: 'azerbaijan' },
        { label: 'Bahamas', value: 'bahamas' },
        { label: 'Bahrain', value: 'bahrain' },
        { label: 'Bangladesh', value: 'bangladesh' },
        { label: 'Barbados', value: 'barbados' },
        { label: 'Belarus', value: 'belarus' },
        { label: 'Belgium', value: 'belgium' },
        { label: 'Belize', value: 'belize' },
        { label: 'Benin', value: 'benin' },
        { label: 'Bhutan', value: 'bhutan' },
        { label: 'Bolivia', value: 'bolivia' },
        { label: 'Bosnia and Herzegovina', value: 'bosnia_and_herzegovina' },
        { label: 'Botswana', value: 'botswana' },
        { label: 'Brazil', value: 'brazil' },
        { label: 'Brunei', value: 'brunei' },
        { label: 'Bulgaria', value: 'bulgaria' },
        { label: 'Burkina Faso', value: 'burkina_faso' },
        { label: 'Burundi', value: 'burundi' },
        { label: 'Cambodia', value: 'cambodia' },
        { label: 'Cameroon', value: 'cameroon' },
        { label: 'Canada', value: 'canada' },
        { label: 'Cape Verde', value: 'cape_verde' },
        { label: 'Central African Republic', value: 'central_african_republic' },
        { label: 'Chad', value: 'chad' },
        { label: 'Chile', value: 'chile' },
        { label: 'China', value: 'china' },
        { label: 'Colombia', value: 'colombia' },
        { label: 'Comoros', value: 'comoros' },
        { label: 'Congo', value: 'congo' },
        { label: 'Costa Rica', value: 'costa_rica' },
        { label: 'Croatia', value: 'croatia' },
        { label: 'Cuba', value: 'cuba' },
        { label: 'Cyprus', value: 'cyprus' },
        { label: 'Czech Republic', value: 'czech_republic' },
        { label: 'Denmark', value: 'denmark' },
        { label: 'Djibouti', value: 'djibouti' },
        { label: 'Dominica', value: 'dominica' },
        { label: 'Dominican Republic', value: 'dominican_republic' },
        { label: 'East Timor', value: 'east_timor' },
        { label: 'Ecuador', value: 'ecuador' },
        { label: 'Egypt', value: 'egypt' },
        { label: 'El Salvador', value: 'el_salvador' },
        { label: 'Equatorial Guinea', value: 'equatorial_guinea' },
        { label: 'Eritrea', value: 'eritrea' },
        { label: 'Estonia', value: 'estonia' },
        { label: 'Ethiopia', value: 'ethiopia' },
        { label: 'Fiji', value: 'fiji' },
        { label: 'Finland', value: 'finland' },
        { label: 'France', value: 'france' },
        { label: 'Gabon', value: 'gabon' },
        { label: 'Gambia', value: 'gambia' },
        { label: 'Georgia', value: 'georgia' },
        { label: 'Germany', value: 'germany' },
        { label: 'Ghana', value: 'ghana' },
        { label: 'Greece', value: 'greece' },
        { label: 'Grenada', value: 'grenada' },
        { label: 'Guatemala', value: 'guatemala' },
        { label: 'Guinea', value: 'guinea' },
        { label: 'Guinea-Bissau', value: 'guinea_bissau' },
        { label: 'Guyana', value: 'guyana' },
        { label: 'Haiti', value: 'haiti' },
        { label: 'Honduras', value: 'honduras' },
        { label: 'Hungary', value: 'hungary' },
        { label: 'Iceland', value: 'iceland' },
        { label: 'India', value: 'india' },
        { label: 'Indonesia', value: 'indonesia' },
        { label: 'Iran', value: 'iran' },
        { label: 'Iraq', value: 'iraq' },
        { label: 'Ireland', value: 'ireland' },
        { label: 'Israel', value: 'israel' },
        { label: 'Italy', value: 'italy' },
        { label: 'Ivory Coast', value: 'ivory_coast' },
        { label: 'Jamaica', value: 'jamaica' },
        { label: 'Japan', value: 'japan' },
        { label: 'Jordan', value: 'jordan' },
        { label: 'Kazakhstan', value: 'kazakhstan' },
        { label: 'Kenya', value: 'kenya' },
        { label: 'Kiribati', value: 'kiribati' },
        { label: 'North Korea', value: 'north_korea' },
        { label: 'South Korea', value: 'south_korea' },
        { label: 'Kuwait', value: 'kuwait' },
        { label: 'Kyrgyzstan', value: 'kyrgyzstan' },
        { label: 'Laos', value: 'laos' },
        { label: 'Latvia', value: 'latvia' },
        { label: 'Lebanon', value: 'lebanon' },
        { label: 'Lesotho', value: 'lesotho' },
        { label: 'Liberia', value: 'liberia' },
        { label: 'Libya', value: 'libya' },
        { label: 'Liechtenstein', value: 'liechtenstein' },
        { label: 'Lithuania', value: 'lithuania' },
        { label: 'Luxembourg', value: 'luxembourg' },
        { label: 'Macedonia', value: 'macedonia' },
        { label: 'Madagascar', value: 'madagascar' },
        { label: 'Malawi', value: 'malawi' },
        { label: 'Malaysia', value: 'malaysia' },
        { label: 'Maldives', value: 'maldives' },
        { label: 'Mali', value: 'mali' },
        { label: 'Malta', value: 'malta' },
        { label: 'Marshall Islands', value: 'marshall_islands' },
        { label: 'Mauritania', value: 'mauritania' },
        { label: 'Mauritius', value: 'mauritius' },
        { label: 'Mexico', value: 'mexico' },
        { label: 'Micronesia', value: 'micronesia' },
        { label: 'Moldova', value: 'moldova' },
        { label: 'Monaco', value: 'monaco' },
        { label: 'Mongolia', value: 'mongolia' },
        { label: 'Montenegro', value: 'montenegro' },
        { label: 'Morocco', value: 'morocco' },
        { label: 'Mozambique', value: 'mozambique' },
        { label: 'Myanmar', value: 'myanmar' },
        { label: 'Namibia', value: 'namibia' },
        { label: 'Nauru', value: 'nauru' },
        { label: 'Nepal', value: 'nepal' },
        { label: 'Netherlands', value: 'netherlands' },
        { label: 'New Zealand', value: 'new_zealand' },
        { label: 'Nicaragua', value: 'nicaragua' },
        { label: 'Niger', value: 'niger' },
        { label: 'Nigeria', value: 'nigeria' },
        { label: 'Norway', value: 'norway' },
        { label: 'Oman', value: 'oman' },
        { label: 'Pakistan', value: 'pakistan' },
        { label: 'Palau', value: 'palau' },
        { label: 'Panama', value: 'panama' },
        { label: 'Papua New Guinea', value: 'papua_new_guinea' },
        { label: 'Paraguay', value: 'paraguay' },
        { label: 'Peru', value: 'peru' },
        { label: 'Philippines', value: 'philippines' },
        { label: 'Poland', value: 'poland' },
        { label: 'Portugal', value: 'portugal' },
        { label: 'Qatar', value: 'qatar' },
        { label: 'Romania', value: 'romania' },
        { label: 'Russia', value: 'russia' },
        { label: 'Rwanda', value: 'rwanda' },
        { label: 'Saint Kitts and Nevis', value: 'saint_kitts_and_nevis' },
        { label: 'Saint Lucia', value: 'saint_lucia' },
        { label: 'Saint Vincent and the Grenadines', value: 'saint_vincent_and_the_grenadines' },
        { label: 'Samoa', value: 'samoa' },
        { label: 'San Marino', value: 'san_marino' },
        { label: 'Sao Tome and Principe', value: 'sao_tome_and_principe' },
        { label: 'Saudi Arabia', value: 'saudi_arabia' },
        { label: 'Senegal', value: 'senegal' },
        { label: 'Serbia', value: 'serbia' },
        { label: 'Seychelles', value: 'seychelles' },
        { label: 'Sierra Leone', value: 'sierra_leone' },
        { label: 'Singapore', value: 'singapore' },
        { label: 'Slovakia', value: 'slovakia' },
        { label: 'Slovenia', value: 'slovenia' },
        { label: 'Solomon Islands', value: 'solomon_islands' },
        { label: 'Somalia', value: 'somalia' },
        { label: 'South Africa', value: 'south_africa' },
        { label: 'South Sudan', value: 'south_sudan' },
        { label: 'Spain', value: 'spain' },
        { label: 'Sri Lanka', value: 'sri_lanka' },
        { label: 'Sudan', value: 'sudan' },
        { label: 'Suriname', value: 'suriname' },
        { label: 'Swaziland', value: 'swaziland' },
        { label: 'Sweden', value: 'sweden' },
        { label: 'Switzerland', value: 'switzerland' },
        { label: 'Syria', value: 'syria' },
        { label: 'Taiwan', value: 'taiwan' },
        { label: 'Tajikistan', value: 'tajikistan' },
        { label: 'Tanzania', value: 'tanzania' },
        { label: 'Thailand', value: 'thailand' },
        { label: 'Togo', value: 'togo' },
        { label: 'Tonga', value: 'tonga' },
        { label: 'Trinidad and Tobago', value: 'trinidad_and_tobago' },
        { label: 'Tunisia', value: 'tunisia' },
        { label: 'Turkey', value: 'turkey' },
        { label: 'Turkmenistan', value: 'turkmenistan' },
        { label: 'Tuvalu', value: 'tuvalu' },
        { label: 'Uganda', value: 'uganda' },
        { label: 'Ukraine', value: 'ukraine' },
        { label: 'United Arab Emirates', value: 'united_arab_emirates' },
        { label: 'United Kingdom', value: 'united_kingdom' },
        { label: 'United States', value: 'united_states' },
        { label: 'Uruguay', value: 'uruguay' },
        { label: 'Uzbekistan', value: 'uzbekistan' },
        { label: 'Vanuatu', value: 'vanuatu' },
        { label: 'Vatican City', value: 'vatican_city' },
        { label: 'Venezuela', value: 'venezuela' },
        { label: 'Vietnam', value: 'vietnam' },
        { label: 'Yemen', value: 'yemen' },
        { label: 'Zambia', value: 'zambia' },
        { label: 'Zimbabwe', value: 'zimbabwe' }
      ]
    },
    {
      id: 'legalStatus',
      group: 'eligibility',
      type: 'select',
      label: 'Legal status',
      required: true,
      options: [
        { label: 'Citizen', value: 'citizen' },
        { label: 'Permanent Resident', value: 'permanent_resident' },
        { label: 'Temporary Resident', value: 'temporary_resident' },
        { label: 'Student', value: 'student' },
        { label: 'Tourist', value: 'tourist' },
        { label: 'Work Visa Holder', value: 'work_visa' },
        { label: 'Refugee/Asylum Seeker', value: 'refugee' },
        { label: 'Other', value: 'other' }
      ]
    },
    
    // Purpose of Stay Section
    {
      id: 'purposeOfStayHeader',
      group: 'travel',
      type: 'header',
      label: 'Purpose of stay'
    },
    {
      id: 'purposeOfStayInfo',
      group: 'travel',
      type: 'info',
      label: '',
      content: ['Select the stream the applicant is applying for:']
    },
    {
      id: 'visaStream',
      group: 'travel',
      type: 'select',
      label: 'Visa stream',
      required: true,
      options: [
        { label: 'Business Visitor stream (business visit for meetings, conferences or negotiations but not for work)', value: 'business_visitor' },
        { label: 'Frequent Traveller stream (tourism or business purposes)', value: 'frequent_traveller' },
        { label: 'Sponsored Family stream (requires Sponsorship form 1149)', value: 'sponsored_family' },
        { label: 'Tourist stream (tourism/visit family or friends)', value: 'tourist' }
      ]
    },
    {
      id: 'streamInfoNote',
      group: 'travel',
      type: 'info',
      label: '',
      content: ['Note: Once the application has been lodged, the stream cannot be changed. For more information on each stream, click on the help icon above.']
    },
    {
      id: 'reasonsForVisit',
      group: 'travel',
      type: 'select',
      label: 'List all reasons for visiting Australia',
      required: true,
      options: [
        { label: 'Tourism/Holiday', value: 'tourism' },
        { label: 'Visit family', value: 'visit_family' },
        { label: 'Visit friends', value: 'visit_friends' },
        { label: 'Business visitor activities', value: 'business' },
        { label: 'Conference/Meeting', value: 'conference' },
        { label: 'Medical treatment', value: 'medical' },
        { label: 'Other', value: 'other' }
      ]
    },
    {
      id: 'significantDates',
      group: 'travel',
      type: 'text',
      label: 'Give details of any significant dates on which the applicant needs to be in Australia',
      required: false
    },
    
    // Group Processing Section
    {
      id: 'groupProcessingHeader',
      group: 'travel',
      type: 'header',
      label: 'Group processing'
    },
    {
      id: 'groupApplication',
      group: 'travel',
      type: 'select',
      label: 'Is this application being lodged as part of a group of applications?',
      required: true,
      options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' }
      ]
    }
  ],
  documents: [
    {
      id: 'passport',
      name: 'Passport',
      description: 'A copy of your passport bio-data page',
      type: 'default',
      required: true,
      extractableFields: [
        {
          fieldId: 'passportNumber',
          source: 'passport'
        },
        {
          fieldId: 'passportExpiryDate',
          source: 'passport'
        }
      ]
    },
    {
      id: 'photo',
      name: 'Photograph',
      description: 'A recent passport-sized photograph (45mm x 35mm)',
      type: 'default',
      required: true
    },
    {
      id: 'financialEvidence',
      name: 'Evidence of financial capacity',
      description: 'Bank statements, pay slips, or other documents showing you have sufficient funds for your stay',
      type: 'default',
      required: true
    }
  ]
};
